require 'slack-timelybot/commands/admin/help'
require 'slack-timelybot/commands/admin/test'
require 'slack-timelybot/commands/admin/check_attendance'
require 'slack-timelybot/commands/admin/founder'
require 'slack-timelybot/commands/admin/init'
require 'slack-timelybot/commands/admin/update'
require 'slack-timelybot/commands/admin/set_mod'
