require 'pry'
require 'sinatra/activerecord'
require 'models/cohort'
require 'models/sheet'
require 'models/user'
require 'launchy'

require 'google_drive'
require 'g-drive/authenticate'
require 'g-drive/session'
require 'g-drive/sheet'
require 'g-drive/worksheet'

require 'slack-ruby-bot'
require 'slack-timelybot/commands'
require 'slack-timelybot/add_methods'
require 'slack-timelybot/bot'
