development:
 adapter: postgresql
 encoding: unicode
 database: im_here_bot
 username: <%= ENV['USERNAME_LOCAL'] =>
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: attendance-slackbot
 username: dokku-postgres-attendance-slackbot
 password: <%= ENV['DB_PASSWORD'] =>
 host: <%= ENV['DB_HOST'] =>
 port: <%= ENV['DB_PORT'] =>
