development:
  url: postgres://jmines@localhost:5432/im_here_bot

production:
 adapter: postgresql
 encoding: unicode
 database: attendance-slackbot
 username: dokku-postgres-attendance-slackbot
 password: <%= ENV['DB_PASSWORD'] =>
 host: <%= ENV['DB_HOST'] =>
 port: <%= ENV['DB_PORT'] =>
